image: docker

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

build:
  stage: build
  only:
    - develop
    - production
  script:
    - sudo apt-get install -y python-pip
    - pip install docker-compose
    - sudo docker image prune -f
    - sudo docker-compose build --no-cache
    
test:
  stage: test
  only:
    - develop
    - production
  script:
    - echo run tests in this section

step-deploy-prod:
  stage: deploy
  only:
    - production
  script:    
    - sudo docker-compose up -d
  environment: production
  when: manual

