version: "3.7"
services:
  web:
    build: ./web
    image: webapp:v1
    ports:
      - "3000:3000"
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    networks:
      - webnet

  todos:
    build: ./todos
    image: todos:v1
    ports:
      - "3001:3000"
      - "7000:7000"
    depends_on:
      - db
    volumes:
      - ./todos:/todos
    command: dockerize -wait tcp://db:27017 -timeout 1m npm run start
    environment:
      - MONGO_DB_URI=mongodb://db:27017/microservicesdb
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    networks:
      - webnet

  db:
    image: mongo   
    networks:
      - webnet
    # volumes:
    #   - ./data:/data/db


  nginx:
    image: nginx:latest
    ports:
      - "8081:8081"
    volumes:
      - ./web/public:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - todos
    networks:
      - webnet


networks: 
  webnet:
