version: "3.7"
services:
  web:
    build: ./web
    image: webapp:v1
    ports:
      - "3000:3000"
    command: npm run prod

  todos:
    build: ./todos
    image: todos:v1
    ports:
      - "3001:3000"
      - "7000:7000"
    depends_on:
      - db
    command: dockerize -wait tcp://db:27017 -timeout 60m npm run prod
    environment:
      - MONGO_DB_URI=mongodb://db:27017/microservicesdb
    
  db:
    image: mongo       
    volumes:
      - ./data:/data/db


  nginx:
    image: nginx:latest
    ports:
      - "8081:8081"
    volumes:
      - ./web/public:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - todos
